vendors:
  "Water Kiosk - Tudor": "6997a063-3fd3-443a-9d0d-d2130c373c4d"
  "Water Kiosk - Diani": "44203f64-de6b-49c1-b8c2-8d06c9edae6c"
  "Tumaqua": "81be27fc-0b16-42de-894d-9b1f23b5d5b2"
  "Dutch Water": "c401b531-719d-4cad-82e7-71db3ffba166"
  "Water Kiosk - Nyali": "add70d88-b7e2-4805-b9be-5738c8696a62"
  "Water Kiosk - Bamburi": "9e04f3d0-88f6-4856-aa17-0fc124a416ae"
  "Water Kiosk - Mwtapa": "c236ebbd-255d-41b5-bb30-1a4fb83b823f"
  "GivePower": "552f6c33-8a62-4fde-b21c-0d7defabb35c"

